### ISSUE TITLE
Provider: kutt.it

### ISSUE THREAD

**Issue by timvisee** [vityafx/urlshortener-rs#16]
How about support for [`kutt.it`](https://kutt.it/)? This would be cool because it's a shortener that is [open-source](https://github.com/thedevs-network/kutt) and easily self hosted in contrast to the current list of supported shorteners. A `kutt.it` instance provides an API and uses an API key.

What do you think? I might have some time to implement a provider for this.

**Comment by iddm** [comment]
Hi! I'll absolutely appreciate having it implemented here! That is what this crate is for :)

**Comment by iddm** [comment]
But, as it is an open-source project, we might extend the urlshortener-rs API to support not only specification of custom API keys for the `kutt.it` url shortener, but also different domains then (if a user wants to self-host it, we should allow one to specify the url pointing to his own `kutt.it`).

**Comment by iddm** [comment]
@timvisee Do you want to implement yourself or?

**Comment by timvisee** [comment]
I'll take a look into this now. Not sure whether I'm able to complete it though, due to limited time.

> but also different domains then

Exactly. I'm thinking of an (optional) provider field now. I'll check how it works out.
