### ISSUE TITLE
The trait `std::error::Error` is not implemented for `ProviderError`, used by `urlshortener::client::UrlShortener::generate`

### ISSUE THREAD

**Issue by Antosser** [vityafx/urlshortener-rs#23]
The trait `std::error::Error` is not implemented for `ProviderError`, used by `urlshortener::client::UrlShortener::generate`.
This means that you can't `?` out of a `-> anyhow::Result<_>` function, which is quite unpractical

**Comment by iddm** [comment]
Yes, this is true. It has been a long time since I last visited the crate. I'll try finding the time to add it.

**Comment by iddm** [comment]
Implemented and published as 3.1.0. Thanks!
