### ISSUE TITLE
Spurious build failures

### ISSUE THREAD

**Issue by ghost** [vityafx/urlshortener-rs#3]
Builds are [spuriously failing](https://travis-ci.org/vityafx/urlshortener-rs/jobs/143511968).

Commit: 2c7dce409105889249877a2fc91833f9b2a7c936

Error:

```
running 1 test

test tests::providers ... FAILED

failures:

---- tests::providers stdout ----

    thread 'tests::providers' panicked at 'assertion failed: us.generate(url, provider).is_ok()', src/lib.rs:158

note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The error obviously wasn't the doc changes, so that leads me to believe it's either:

a. the 3 second timeout on the hyper request is not enough time to generate a URL for some services; or
b. the service simply did not respond

So this leads me to suggest one of three courses of action:
1. Create a check in the test, where if the result of a `generate` call is a "Service is unavailable" error, then to either:
   
   a. skip the provider for the build and assume it works;
   b. re-try the provider up to 3 times;
2. Increase the maximum time per request to a 5 second timeout;
3. ignore provider errors (this essentially invalidates the tests). Instead, we test against sample stored outputs of each of these services, and simply check that decoding them works.

Personally, I prefer option 1A. I think that allowing over 3 seconds for a provider is too long (using `try_generate` would fix this, as it'd simply attempt the next provider), and re-trying probably wouldn't matter, because the service likely would still be slower than usual within a 1-minute window.

**Comment by iddm** [comment]
The problem is that on a my development machine the tests are good. It seems travis's connection is bad for this kind of testing.
