### ISSUE TITLE
Parsing issue with bit.ly when long url contains "#"

### ISSUE THREAD

**Issue by arshubham** [vityafx/urlshortener-rs#9]
ex: Long Url: ```google.com/asd#123```
Output :
```{"status_code":200,"status_txt":"OK","data":{"url":"http://bit.ly/2nYsQDH","hash":"2nYsQDH","global_hash":"ipdYoe","long_url":"http://google.com/asd","new_hash":0}}```

**Comment by iddm** [comment]
Looks like we or the service truncates the anchor from the url. I think this is the `urlshortener` crate itself because, I think, it does not properly encode the url to the percent encoding.

This can be fixed with something like this:

```rust
use url::percent_encoding::{utf8_percent_encode, SIMPLE_ENCODE_SET};
define_encode_set! {
    /// This encode set is used in the URL parser for query strings.
    pub QUERY_ENCODE_SET = [SIMPLE_ENCODE_SET] | {' ', '"', '#', '<', '>'}
}

fn main() {
    assert_eq!(utf8_percent_encode("http://google.com/asd#123", QUERY_ENCODE_SET).collect::<String>(), "http://google.com/asd%23123");
}
```

**Comment by iddm** [comment]
@arshubham Would you like to try fixing this? The solution seems to be quite simple.

**Comment by arshubham** [comment]
Yeah, that would be great. Will make a pull by tomorrow.
